version: "3.8"

services:
  frontend:
    container_name: frontend

    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"

    ports:
      - 5173:5173

    command: npm run dev -- --host
